version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: 'yatc-mongo'
    environment:
      - MONGO_INITDB_DATABASE=yatc-db
      - MONGO_INITDB_ROOT_USERNAME=xiuxiu
      - MONGO_INITDB_ROOT_PASSWORD=givemethatsauce!!givemethatsauce
    ports:
      - '27017-27019:27017-27019'
  # nginx:
  #   image: nginx:latest
  #   deploy:
  #     replicas: 1
  #   configs:
  #     - my_config
  #     - my_other_config
